services:
  postgres:
    build:
      context: .
      dockerfile: postgres.dockerfile
    image: "postgres-test"
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
       - dbtest:/data/postgres-test
    ports:
      - "5433:5432"
    restart: unless-stopped
volumes:
    dbtest:
      external: true